In [2]:
import numpy as np

In [3]:
trainMatrix = np.genfromtxt('spam_data/trainMatrix.csv', delimiter=',')

np.save('trainMatrix', trainMatrix)

testMatrix = np.genfromtxt('spam_data/testMatrix.csv', delimiter=',')

np.save('testMatrix', testMatrix)

OSError: spam_data/trainMatrix.csv not found.

In [13]:
testMatrix.shape

(800, 1448)

In [24]:
print(trainMatrix.shape)

(2144, 1448)


In [53]:
import numpy as np
# a = np.random.randint(5, size=(2, 5))
b = np.random.randint(10, size=(3,3,3))
a = np.random.randint(10, size=(3,3))
print(a)
b

[[0 1 5]
 [7 2 4]
 [3 4 3]]


array([[[8, 2, 2],
        [0, 4, 1],
        [6, 2, 0]],

       [[1, 6, 5],
        [2, 1, 0],
        [0, 5, 8]],

       [[9, 4, 5],
        [0, 5, 1],
        [8, 3, 2]]])

In [55]:
np.where(a<3, b, 0)

array([[[8, 2, 2],
        [0, 4, 1],
        [6, 2, 0]],

       [[1, 6, 5],
        [0, 1, 0],
        [0, 5, 8]],

       [[9, 4, 5],
        [0, 5, 1],
        [8, 3, 2]]])

In [59]:
b[a<3]

array([[8, 2, 2],
       [0, 4, 1],
       [2, 1, 0]])

In [58]:
a < 6

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True]])